### ISSUE TITLE
Oedialect has_schema not working

### ISSUE THREAD

**Issue by henhuy** [OpenEnergyPlatform/oedialect#48]
Recently, oedialect does not work anymore. Maybe newest OEP update has crashed something? (I think the error occurred after release). When I try to run `has_schema` it gives me following error:
`oedialect.engine.ConnectionException: HTTP 405 (Method Not Allowed)`
Any idea?

**Versions:**
oedialect          0.0.10
SQLAlchemy         1.3.14

**Minimal Example:**
```
import os
import oedialect  # noqa
import sqlalchemy as sa
OEP_CONNECTION = "postgresql+oedialect://{user}:{token}@openenergyplatform.org"

user = os.environ["USER"]
token = os.environ["TOKEN"]

conn_str = OEP_CONNECTION.format(user=user, token=token)
engine = sa.create_engine(conn_str)
metadata = sa.MetaData(bind=engine)
print(engine.dialect.has_schema(engine, "model_draft"))
```

Error Traceback:
```
Traceback (most recent call last):
  File "/home/hendrik/.config/JetBrains/PyCharm2024.1/scratches/scratch_4.py", line 12, in <module>
    print(engine.dialect.has_schema(engine, "model_draft"))
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/oedialect/dialect.py", line 286, in has_schema
    return self.execute_with_cursor(
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/oedialect/dialect.py", line 273, in execute_with_cursor
    with connection.connect() as conn:
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2218, in connect
    return self._connection_cls(self, **kwargs)
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 103, in __init__
    else engine.raw_connection()
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2317, in raw_connection
    return self._wrap_pool_connect(
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
    return fn()
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 657, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
    connection = pool._invoke_creator(self)
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 488, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/oedialect/dbapi.py", line 7, in connect
    return OEConnection(**kwargs)
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/oedialect/engine.py", line 45, in __init__
    response = self.post("advanced/connection/open", {})["content"]
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/oedialect/engine.py", line 248, in post
    process_returntype(ans, json_response)
  File "/home/hendrik/miniconda3/envs/oedatamodel_api/lib/python3.9/site-packages/oedialect/engine.py", line 262, in process_returntype
    raise ConnectionException(
oedialect.engine.ConnectionException: HTTP 405 (Method Not Allowed): 
```

**Comment by jh-RLI** [comment]
I think i found the reason. For me (using your script) this is solved when i change the OEP url here in the oedialect engine https://github.com/OpenEnergyPlatform/oedialect/blob/4b6676da39db8494b062304511b48df5c2fb875a/oedialect/engine.py#L166 

to: "openenergyplatform.org"

This is related to our recent server update. The redirect from old to new url now drops the request headers for some reason. If you can verify this i will create a fix & new oedialect release.
